version: "2"
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/openvpn:/etc/openvpn
    ports:
      - 1194:1194/udp
    restart: unless-stopped