version: "2"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    restart: unless-stopped