version: "2"
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /media/Volume0:/downloads/Volume0
      - /media/Volume1:/downloads/Volume1
      - /media/Volume2:/downloads/Volume2
      - /opt/transmission/config:/config
    restart: unless-stopped
