version: "2"
services:
  wireguard:
    image: cmulk/wireguard-docker:buster
    container_name: wireguard
    ports:
     - 5555:5555/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE